/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bczzlvhjaorneddwhisd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjenpsdmhqYW9ybmVkZHdoaXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODQyNzYsImV4cCI6MjA3MzM2MDI3Nn0.ytP7-p-NZXiynHAY_ZSHiVcmvgltSMCt8P_rLpfVikg"