// Timeline constants
export const TIMELINE_ACTIONS = {
  // Block management
  ADD_BLOCK: 'ADD_BLOCK',
  UPDATE_BLOCK: 'UPDATE_BLOCK',
  DELETE_BLOCK: 'DELETE_BLOCK',
  SELECT_BLOCK: 'SELECT_BLOCK',
  DUPLICATE_BLOCK: 'DUPLICATE_BLOCK',
  
  // Block arrangement
  MOVE_BLOCK: 'MOVE_BLOCK',
  RESIZE_BLOCK: 'RESIZE_BLOCK',
  SPLIT_BLOCK: 'SPLIT_BLOCK',
  MERGE_BLOCKS: 'MERGE_BLOCKS',
  
  // Timeline controls
  SET_ZOOM: 'SET_ZOOM',
  SET_SCROLL: 'SET_SCROLL',
  SET_BPM: 'SET_BPM',
  SET_TIME_SIGNATURE: 'SET_TIME_SIGNATURE',
  
  // Playback
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  STOP: 'STOP',
  SEEK: 'SEEK',
  
  // Lyrics and style
  UPDATE_LYRICS: 'UPDATE_LYRICS',
  UPDATE_STYLE: 'UPDATE_STYLE',
  
  // Import/Export
  LOAD_PROJECT: 'LOAD_PROJECT',
  SAVE_PROJECT: 'SAVE_PROJECT'
};
